force-app/main/default/objects/Account/fields/CollectionsStatus__c.field-meta.xml
<CustomField>
    <fullName>CollectionsStatus__c</fullName>
    <inlineHelpText>Current Collections Status for this Account</inlineHelpText>
    <label>Collections Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Current</fullName>
                <default>true</default>
                <label>Current</label>
            </value>
            <value>
                <fullName>Pending Collections</fullName>
            </value>
            <value>
                <fullName>In Collections</fullName>
            </value>
            <value>
                <fullName>Credit Hold</fullName>
            </value>
            <value>
                <fullName>Bad Debt</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/DunningMethod__c.field-meta.xml
<CustomField>
    <fullName>DunningMethod__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Dunning Method associated to the account. Used when the account&apos;s Collection Status is not current.</description>
    <inlineHelpText>Dunning Method that will be run when the account&apos;s Collection Status is not current.</inlineHelpText>
    <label>Dunning Method</label>
    <referenceTo>DunningMethod__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CollectionsInvoice__c/CollectionsInvoice__c.object-meta.xml
<CustomObject>
    <description>Junction object to link Invoices to Collection Plans</description>
    <label>Collections Invoice</label>
    <nameField>
        <displayFormat>CI-{000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Collections Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CollectionsInvoice__c/fields/CollectionsPlan__c.field-meta.xml
<CustomField>
    <fullName>CollectionsPlan__c</fullName>
    <label>Collections Plan</label>
    <referenceTo>CollectionsPlan__c</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Collections_Invoices</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/CollectionsPlan__c/CollectionsPlan__c.object-meta.xml
<CustomObject>
    <description>Collections Plans track collections activites and related invoices.</description>
    <label>Collections Plan</label>
    <nameField>
        <displayFormat>Collections #{000000}</displayFormat>
        <label>Collections Plan Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Collections Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CollectionsPlan__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Account that is related to this Collections Plan</description>
    <inlineHelpText>Account associated with this Collections Plan</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Collections Plans</relationshipLabel>
    <relationshipName>Collections_Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CollectionsPlan__c/fields/DunningMethod__c.field-meta.xml
<CustomField>
    <fullName>DunningMethod__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The associated Dunning Method that created this Collections Plan.</description>
    <inlineHelpText>The associated Dunning Method that created this Collections Plan.</inlineHelpText>
    <label>Dunning Method</label>
    <referenceTo>DunningMethod__c</referenceTo>
    <relationshipLabel>Collections Plans</relationshipLabel>
    <relationshipName>Collections_Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DunningActivity__c/DunningActivity__c.object-meta.xml
<CustomObject>
    <description>Dunning Activities are templates for tasks that will be created on a Collections Plan from a Dunning Method.</description>
    <label>Dunning Activity</label>
    <nameField>
        <label>Dunning Activity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dunning Activities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DunningActivity__c/fields/DunningMethod__c.field-meta.xml
<CustomField>
    <fullName>DunningMethod__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Dunning Method associated with this Dunning Activity</description>
    <inlineHelpText>Dunning Method for this Dunning Activity</inlineHelpText>
    <label>Dunning Method</label>
    <referenceTo>DunningMethod__c</referenceTo>
    <relationshipLabel>Dunning Activities</relationshipLabel>
    <relationshipName>Dunning_Activities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DunningMethod__c/DunningMethod__c.object-meta.xml
<CustomObject>
    <description>Entity to manage Dunning notices / activities.</description>
    <label>Dunning Method</label>
    <nameField>
        <label>Dunning Method Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dunning Methods</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/DunningAccountTriggerHandler.cls
public with sharing class DunningAccountTriggerHandler {
   static final String IN_COLLECTIONS = 'In Collections';

    public static void handleAfterUpdate(Map<Id,Account> oldAccountMap, Map<Id,Account> newAccountMap) {
        Map<Id, Account> accountsInCollections = new Map<Id, Account>();

        // Check if the Collections Status field is changed
        for(Id accId: oldAccountMap.keySet()) {
            // Check if the old value was NOT in collections and that the new value IS in collections
            // also check if Dunning Method is set on account
            String oldStatus = oldAccountMap.get(accId).CollectionsStatus__c;
            String newStatus = newAccountMap.get(accId).CollectionsStatus__c;
            Id dunningMethodId = newAccountMap.get(accId).DunningMethod__c;
            if( oldStatus != IN_COLLECTIONS && newStatus == IN_COLLECTIONS && dunningMethodId != null) {
                accountsInCollections.put(accId, newAccountMap.get(accId));
            }
            
        }

        if(accountsInCollections.isEmpty()) {
            return;
        }
        // Get Dunning Methods
        Map<Id,Id> dunningIdByAccountId = DunningUtilities.getDunningIdsFromAccounts(accountsInCollections.values());


        Set<Id> dunningMethodIds = new Set<Id>();
        dunningMethodIds.addAll(dunningIdByAccountId.values());
        // Get Activities by their associated Dunning Id
        Map<Id, List<DunningActivity__c>> activitiesByDunningId = DunningUtilities.getDunningActivities(dunningMethodIds);

        // Create Collections Plans for accounts
        List<CollectionsPlan__c> collectionsPlans = DunningUtilities.createPlansFromAccounts(accountsInCollections.values());

        try {
            Database.insert(collectionsPlans);
        } catch (DmlException e) {
            System.debug(e);
        }

        // Need collections plans by account Ids
        Map<Id,CollectionsPlan__c> plansByAccountId = new Map<Id,CollectionsPlan__c>();
        for (CollectionsPlan__c plan : collectionsPlans) {
            plansByAccountId.put(plan.Account__c, plan);
        }

        // need all Invoices (that should be included) by account Ids
        Map<Id, List<blng__Invoice__c>> invoicesByAccountId = DunningUtilities.getInvoicesFromCollections(plansByAccountId);
        
        // Create the Collection Invoices (link Invoices to Collections plans)
        List<CollectionsInvoice__c> collectInvs = DunningUtilities.createPlanInvoiceJunctions(plansByAccountId, invoicesByAccountId);

        try {
            Database.insert(collectInvs);
        } catch (DmlException e) {
            System.debug(e);
        }


        // Create Tasks on the Collections plans
        List<Task> planTasks = DunningUtilities.createCollectionsTasks(collectionsPlans, activitiesByDunningId);
        // Need Dunning activities from Dunning Method 

        try {
            Database.insert(planTasks);
        } catch (DmlException e) {
            System.debug(e);
        }

    }
}