force-app/main/default/objects/Account/fields/CollectionsAgent__c.field-meta.xml
<CustomField>
    <fullName>CollectionsAgent__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>User that will be assigned any tasks and activities from a Collections Plan on this account.</description>
    <inlineHelpText>User that will be assigned any tasks and activities from a Collections Plan on this account.</inlineHelpText>
    <label>Collections Agent</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/CollectionsPlanDate__c.field-meta.xml
<CustomField>
    <fullName>CollectionsPlanDate__c</fullName>
    <label>Collections Plan Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/CollectionsStatus__c.field-meta.xml
<CustomField>
    <fullName>CollectionsStatus__c</fullName>
    <inlineHelpText>Current Collections Status for this Account</inlineHelpText>
    <label>Collections Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Current</fullName>
                <default>true</default>
                <label>Current</label>
            </value>
            <value>
                <fullName>Pending Collections</fullName>
            </value>
            <value>
                <fullName>In Collections</fullName>
            </value>
            <value>
                <fullName>Credit Hold</fullName>
            </value>
            <value>
                <fullName>Bad Debt</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/DunningMethod__c.field-meta.xml
<CustomField>
    <fullName>DunningMethod__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Dunning Method associated to the account. Used when the account&apos;s Collection Status is not current.</description>
    <inlineHelpText>Dunning Method that will be run when the account&apos;s Collection Status is not current.</inlineHelpText>
    <label>Dunning Method</label>
    <referenceTo>DunningMethod__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CollectionsInvoice__c/CollectionsInvoice__c.object-meta.xml
<CustomObject>
    <description>Junction object to link Invoices to Collection Plans</description>
    <label>Collections Invoice</label>
    <nameField>
        <displayFormat>CI-{000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Collections Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CollectionsInvoice__c/fields/CollectionsPlan__c.field-meta.xml
<CustomField>
    <fullName>CollectionsPlan__c</fullName>
    <label>Collections Plan</label>
    <referenceTo>CollectionsPlan__c</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Collections_Invoices</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/CollectionsInvoice__c/fields/Invoice__c.field-meta.xml
<CustomField>
    <fullName>Invoice__c</fullName>
    <label>Invoice</label>
    <referenceTo>blng__Invoice__c</referenceTo>
    <relationshipLabel>Collections Plans</relationshipLabel>
    <relationshipName>Collections_Invoices</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/CollectionsPlan__c/CollectionsPlan__c.object-meta.xml
<CustomObject>
    <description>Collections Plans track collections activites and related invoices.</description>
    <label>Collections Plan</label>
    <nameField>
        <displayFormat>Collections #{000000}</displayFormat>
        <label>Collections Plan Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Collections Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CollectionsPlan__c/fields/CollectionsAgent__c.field-meta.xml
<CustomField>
    <fullName>CollectionsAgent__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Collections Agent</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Collections_Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CollectionsPlan__c/fields/DunningMethod__c.field-meta.xml
<CustomField>
    <fullName>DunningMethod__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The associated Dunning Method that created this Collections Plan.</description>
    <inlineHelpText>The associated Dunning Method that created this Collections Plan.</inlineHelpText>
    <label>Dunning Method</label>
    <referenceTo>DunningMethod__c</referenceTo>
    <relationshipLabel>Collections Plans</relationshipLabel>
    <relationshipName>Collections_Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DunningActivity__c/DunningActivity__c.object-meta.xml
<CustomObject>
    <description>Dunning Activities are templates for tasks that will be created on a Collections Plan from a Dunning Method.</description>
    <label>Dunning Activity</label>
    <nameField>
        <label>Dunning Activity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dunning Activities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DunningActivity__c/fields/ActivityDetails__c.field-meta.xml
<CustomField>
    <fullName>ActivityDetails__c</fullName>
    <description>Description of this Activity. Maps to the Task Comments field when Collections Plans are generated from the related Dunning Method.</description>
    <inlineHelpText>Description of this Activity. Maps to the Task Comments field when Collections Plans are generated from the related Dunning Method.</inlineHelpText>
    <label>Activity Details</label>
    <length>32000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/DunningActivity__c/fields/ActivitySubject__c.field-meta.xml
<CustomField>
    <fullName>ActivitySubject__c</fullName>
    <description>Subject of this Activity. Maps to the Task Subject field when Collections Plans are created from the related Dunning Method.</description>
    <inlineHelpText>Subject of this Activity. Maps to the Task Subject field when Collections Plans are created from the related Dunning Method.</inlineHelpText>
    <label>Activity Subject</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Call</fullName>
            </value>
            <value>
                <fullName>Email</fullName>
            </value>
            <value>
                <fullName>Send Letter</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DunningActivity__c/fields/DunningMethod__c.field-meta.xml
<CustomField>
    <fullName>DunningMethod__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Dunning Method associated with this Dunning Activity</description>
    <inlineHelpText>Dunning Method for this Dunning Activity</inlineHelpText>
    <label>Dunning Method</label>
    <referenceTo>DunningMethod__c</referenceTo>
    <relationshipLabel>Dunning Activities</relationshipLabel>
    <relationshipName>Dunning_Activities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DunningActivity__c/fields/OffsetDays__c.field-meta.xml
<CustomField>
    <fullName>OffsetDays__c</fullName>
    <description>Number of days to offset a task from a Collections Plan start date.</description>
    <inlineHelpText>Number of days to offset a task from a Collections Plan start date.</inlineHelpText>
    <label>Offset Days</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/DunningMethod__c/DunningMethod__c.object-meta.xml
<CustomObject>
    <description>Entity to manage Dunning notices / activities.</description>
    <label>Dunning Method</label>
    <nameField>
        <label>Dunning Method Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dunning Methods</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DunningSettings__c/DunningSettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Settings to control Dunning Process</description>
    <label>Dunning Settings</label>
</CustomObject>

force-app/main/default/objects/DunningSettings__c/fields/DisableTriggers__c.field-meta.xml
<CustomField>
    <fullName>DisableTriggers__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Controls if triggers from the Dunning Package run. If checked, no package triggers will run. Unchecked will provide normal behavior.</description>
    <inlineHelpText>Controls if triggers from the Dunning Package run. If checked, no package triggers will run. Unchecked will provide normal behavior.</inlineHelpText>
    <label>Disable Triggers</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/DunningAccountTriggerHandlerTest.cls
@isTest
private class DunningAccountTriggerHandlerTest {
    @testSetup
    private static void setup() {
        // Init Custom settings
        DunningSettings__c newCS = new DunningSettings__c();
        newCS.DisableTriggers__c = false;
        Database.insert(newCS);

        // Dunning Method
        DunningMethod__c dm = new DunningMethod__c(Name='Test Dunning Method');
        Database.insert(dm);

        // Dunning Activities
        List<DunningActivity__c> actvs = new List<DunningActivity__c>();
        actvs.add(new DunningActivity__c(Name='Test Call',
                                        ActivitySubject__c='Call', 
                                        ActivityDetails__c='Call the customer',
                                        OffsetDays__c=3,
                                        DunningMethod__c=dm.Id));

        actvs.add(new DunningActivity__c(Name='Test Email',
                                        ActivitySubject__c='Email', 
                                        ActivityDetails__c='Email the customer',
                                        OffsetDays__c=2,
                                        DunningMethod__c=dm.Id));

        Database.insert(actvs);

        // insert account
        Account testAcc = new Account(Name='Test Account',
                                        DunningMethod__c=dm.Id);
        Database.insert(testAcc);

        // Contact
        Contact testContact = new Contact(AccountId=testAcc.Id,
                                        FirstName='Test',
                                        LastName='User');
        Database.insert(testContact);

        // Invoice
        blng__Invoice__c inv = new blng__Invoice__c(blng__Account__c=testAcc.Id,
                                                    blng__InvoiceStatus__c='Posted',
                                                    blng__DueDate__c=System.today().addDays(-2));
        Database.insert(inv);

        // Invoice Line
        blng__InvoiceLine__c invLine = new blng__InvoiceLine__c(blng__Invoice__c=inv.Id,
                                                                Name='Test Product',
                                                                blng__Quantity__c=1,
                                                                blng__UnitPrice__c=50,
                                                                blng__Subtotal__c=50,
                                                                blng__TaxAmount__c=0,
                                                                blng__TotalAmount__c=50);
        Database.insert(invLine);
    }

    @isTest
    private static void inCollectionsUpdateTest() {
        Id accId = [SELECT Id FROM Account LIMIT 1].Id;
        Map<Id,Account> oldAccountMap = new Map<Id,Account>([SELECT 
                                                                Id, 
                                                                Name, 
                                                                DunningMethod__c, 
                                                                CollectionsPlanDate__c,
                                                                CollectionsAgent__c,
                                                                CollectionsStatus__c,
                                                                OwnerId,
                                                                blng__BillToContact__c
                                                            FROM Account 
                                                            LIMIT 1]);
        

        Map<Id,Account> newAccountMap = oldAccountMap.deepClone();
        Account newAcc = newAccountMap.get(accId);

        newAcc.CollectionsStatus__c = 'In Collections';
        
        DunningAccountTriggerHandler.handleAfterUpdate(oldAccountMap,newAccountMap);

        List<CollectionsPlan__c> collectPlan = [SELECT Id FROM CollectionsPlan__c];
        System.assert(collectPlan.size()>0, 'Collection Plans were created!');

        List<Task> collectionTasks = [SELECT Id FROM Task];
        System.assert(collectionTasks.size()>0, 'Tasks were created!');

        List<CollectionsInvoice__c> collectJXNs = [SELECT Id, CollectionsPlan__c, Invoice__c FROM CollectionsInvoice__c];
        System.assert(collectJXNs.size()>0, 'Junctions were created!');
    }

    @isTest
    private static void notInCollectionsUpdateTest() {
        Id accId = [SELECT Id FROM Account LIMIT 1].Id;
        Map<Id,Account> oldAccountMap = new Map<Id,Account>([SELECT 
                                                                Id, 
                                                                Name, 
                                                                DunningMethod__c, 
                                                                CollectionsPlanDate__c,
                                                                CollectionsAgent__c,
                                                                CollectionsStatus__c,
                                                                OwnerId,
                                                                blng__BillToContact__c
                                                            FROM Account 
                                                            LIMIT 1]);
        

        Map<Id,Account> newAccountMap = oldAccountMap.deepClone();
        
        // Testing where account is not in collections
        DunningAccountTriggerHandler.handleAfterUpdate(oldAccountMap,newAccountMap);

        List<CollectionsPlan__c> collectPlan = [SELECT Id FROM CollectionsPlan__c];
        System.assert(collectPlan.size() == 0, 'No Collection Plans were created!');

        List<Task> collectionTasks = [SELECT Id FROM Task];
        System.assert(collectionTasks.size() == 0, 'No Tasks were created!');

        List<CollectionsInvoice__c> collectJXNs = [SELECT Id, CollectionsPlan__c, Invoice__c FROM CollectionsInvoice__c];
        System.assert(collectJXNs.size() == 0, 'No Junctions were created!');
    }

    @isTest
    private static void noDunningUpdateTest() {
        Id accId = [SELECT Id FROM Account LIMIT 1].Id;
        Map<Id,Account> oldAccountMap = new Map<Id,Account>([SELECT 
                                                                Id, 
                                                                Name, 
                                                                DunningMethod__c, 
                                                                CollectionsPlanDate__c,
                                                                CollectionsAgent__c,
                                                                CollectionsStatus__c,
                                                                OwnerId,
                                                                blng__BillToContact__c
                                                            FROM Account 
                                                            LIMIT 1]);
        

        Map<Id,Account> newAccountMap = oldAccountMap.deepClone();

        Account newAcc = newAccountMap.get(accId);
        // set dunning method to null
        newAcc.DunningMethod__c = null;
        
        // Testing where account does not have a dunning method associated
        DunningAccountTriggerHandler.handleAfterUpdate(oldAccountMap,newAccountMap);

        List<CollectionsPlan__c> collectPlan = [SELECT Id FROM CollectionsPlan__c];
        System.assert(collectPlan.size() == 0, 'No Collection Plans were created!');

        List<Task> collectionTasks = [SELECT Id FROM Task];
        System.assert(collectionTasks.size() == 0, 'No Tasks were created!');

        List<CollectionsInvoice__c> collectJXNs = [SELECT Id, CollectionsPlan__c, Invoice__c FROM CollectionsInvoice__c];
        System.assert(collectJXNs.size() == 0, 'No Junctions were created!');
    }

    @isTest
    private static void triggerDisablerTest() {
        // Turn off triggers in Custom settings
        DunningSettings__c existingCS = DunningSettings__c.getOrgDefaults();
        existingCS.DisableTriggers__c = true;
        Database.update(existingCS);

        // update account
        Account testAcc = [SELECT 
                                Id, 
                                Name, 
                                DunningMethod__c, 
                                CollectionsPlanDate__c,
                                CollectionsAgent__c,
                                CollectionsStatus__c,
                                OwnerId,
                                blng__BillToContact__c
                            FROM Account 
                            LIMIT 1];
        testAcc.DunningMethod__c = null;
        Database.update(testAcc);

        List<CollectionsPlan__c> collectPlan = [SELECT Id FROM CollectionsPlan__c];
        System.assert(collectPlan.size() == 0, 'No Collection Plans were created!');

        List<Task> collectionTasks = [SELECT Id FROM Task];
        System.assert(collectionTasks.size() == 0, 'No Tasks were created!');

        List<CollectionsInvoice__c> collectJXNs = [SELECT Id, CollectionsPlan__c, Invoice__c FROM CollectionsInvoice__c];
        System.assert(collectJXNs.size() == 0, 'No Junctions were created!');
    }
}