force-app/main/default/objects/Account/fields/DunningMethod__c.field-meta.xml
<CustomField>
    <fullName>DunningMethod__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Dunning Method associated to the account. Used when the account&apos;s Collection Status is not current.</description>
    <inlineHelpText>Dunning Method that will be run when the account&apos;s Collection Status is not current.</inlineHelpText>
    <label>Dunning Method</label>
    <referenceTo>DunningMethod__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CollectionsPlan__c/CollectionsPlan__c.object-meta.xml
<CustomObject>
    <description>Collections Plans track collections activites and related invoices.</description>
    <label>Collections Plan</label>
    <nameField>
        <displayFormat>Collections #{000000}</displayFormat>
        <label>Collections Plan Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Collections Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CollectionsPlan__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Account that is related to this Collections Plan</description>
    <inlineHelpText>Account associated with this Collections Plan</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Collections Plans</relationshipLabel>
    <relationshipName>Collections_Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CollectionsPlan__c/fields/CollectionsContact__c.field-meta.xml
<CustomField>
    <fullName>CollectionsContact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Contact that collection tasks are related to by default. Maps from the Account Bill To Contact.</description>
    <inlineHelpText>Contact that collection tasks are related to by default. Maps from the Account Bill To Contact.</inlineHelpText>
    <label>Collections Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Collections Plans</relationshipLabel>
    <relationshipName>Collections_Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CollectionsPlan__c/fields/DunningMethod__c.field-meta.xml
<CustomField>
    <fullName>DunningMethod__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The associated Dunning Method that created this Collections Plan.</description>
    <inlineHelpText>The associated Dunning Method that created this Collections Plan.</inlineHelpText>
    <label>Dunning Method</label>
    <referenceTo>DunningMethod__c</referenceTo>
    <relationshipLabel>Collections Plans</relationshipLabel>
    <relationshipName>Collections_Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CollectionsPlan__c/fields/StartDate__c.field-meta.xml
<CustomField>
    <fullName>StartDate__c</fullName>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/CollectionsPlan__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Current status of this Collections Plan. &apos;Open&apos; is an active Collections Plan, &apos;Closed&apos; is an inactive Collections Plan.</description>
    <inlineHelpText>Current status of this Collections Plan. &apos;Open&apos; is an active Collections Plan, &apos;Closed&apos; is an inactive Collections Plan.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DunningMethod__c/DunningMethod__c.object-meta.xml
<CustomObject>
    <description>Entity to manage Dunning notices / activities.</description>
    <label>Dunning Method</label>
    <nameField>
        <label>Dunning Method Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dunning Methods</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DunningSettings__c/DunningSettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Settings to control Dunning Process</description>
    <label>Dunning Settings</label>
</CustomObject>

force-app/main/default/objects/DunningSettings__c/fields/DisableTriggers__c.field-meta.xml
<CustomField>
    <fullName>DisableTriggers__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Controls if triggers from the Dunning Package run. If checked, no package triggers will run. Unchecked will provide normal behavior.</description>
    <inlineHelpText>Controls if triggers from the Dunning Package run. If checked, no package triggers will run. Unchecked will provide normal behavior.</inlineHelpText>
    <label>Disable Triggers</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/DunningCollectionsTriggerHandlerTest.cls
@isTest
private class DunningCollectionsTriggerHandlerTest {
    @testSetup
    private static void setup() {
        Date planStartDate = System.today();

        // Init Custom settings
        DunningSettings__c newCS = new DunningSettings__c();
        newCS.DisableTriggers__c = false;
        Database.insert(newCS);

        // Dunning Method
        DunningMethod__c dm = new DunningMethod__c(Name='Test Dunning Method');
        Database.insert(dm);

        // insert account
        Account testAcc = new Account(Name='Test Account',
                                        DunningMethod__c=dm.Id);
        Database.insert(testAcc);

        // Contact
        Contact testContact = new Contact(AccountId=testAcc.Id,
                                        FirstName='Test',
                                        LastName='User');
        Database.insert(testContact);

        CollectionsPlan__c colPlan = new CollectionsPlan__c(Status__c='Open',
                                                        StartDate__c=planStartDate,
                                                        Account__c=testAcc.Id,
                                                        DunningMethod__c=dm.Id,
                                                        CollectionsContact__c=testContact.Id);

        Database.insert(colPlan);

        // Collections Tasks
        List<Task> collectTasks = new List<Task>();
        collectTasks.add(new Task(Subject='Call -10', 
                                Description='-10',
                                Status='Not Started',
                                ActivityDate=planStartDate-10,
                                WhatId=colPlan.Id,
                                WhoId=testContact.Id));

        collectTasks.add(new Task(Subject='Email -1', 
                                Description='-1',
                                Status='Not Started', 
                                ActivityDate=planStartDate-1,
                                WhatId=colPlan.Id,
                                WhoId=testContact.Id));

        collectTasks.add(new Task(Subject='Call +10', 
                                Description='10',
                                Status='Not Started',
                                ActivityDate=planStartDate+10,
                                WhatId=colPlan.Id,
                                WhoId=testContact.Id));

        collectTasks.add(new Task(Subject='Email +1',
                                Description='1',
                                Status='Not Started', 
                                ActivityDate=planStartDate+1,
                                WhatId=colPlan.Id,
                                WhoId=testContact.Id));

        Database.insert(collectTasks);

    }

    @isTest
    private static void collectionsUpdateTest() {
        Id planId = [SELECT Id FROM CollectionsPlan__c LIMIT 1].Id;
        Map<Id,CollectionsPlan__c> oldColPlanMap = new Map<Id,CollectionsPlan__c>([SELECT 
                                            Id,
                                            Status__c,
                                            StartDate__c,
                                            Account__c,
                                            DunningMethod__c,
                                            CollectionsContact__c 
                                    FROM CollectionsPlan__c 
                                    LIMIT 1]);

        Map<Id,CollectionsPlan__c> newColPlanMap = oldColPlanMap.deepClone();
        CollectionsPlan__c newPlan = newColPlanMap.get(planId);

        newPlan.Status__c = 'Closed';


        List<Task> collectionTasks = [SELECT Id, 
                                            Subject, 
                                            Description,
                                            Status,
                                            ActivityDate,
                                            WhatId,
                                            WhoId 
                                        FROM Task];
        Integer existingTaskLength = collectionTasks.size();

        for(Task ct :collectionTasks) {
            if(ct.ActivityDate <= System.today()) {
                ct.Status = 'Completed';
            }
        }

        Database.update(collectionTasks);
        
        DunningCollectionsTriggerHandler.handleAfterUpdate(oldColPlanMap,newColPlanMap);

       List<Task> collectionTasksAfter = [SELECT Id, 
                                            Subject, 
                                            Description,
                                            Status,
                                            ActivityDate,
                                            WhatId,
                                            WhoId,
                                            IsClosed
                                        FROM Task];
        System.assert(collectionTasksAfter.size() < existingTaskLength, 'Some Tasks were closed!');
        for(Task ct :collectionTasksAfter) {
            System.assert(ct.IsClosed == true, 'Task is closed');
        }
    }


    @isTest
    private static void triggerDisablerTest() {
        // Turn off triggers in Custom settings
        DunningSettings__c existingCS = DunningSettings__c.getOrgDefaults();
        existingCS.DisableTriggers__c = true;
        Database.update(existingCS);


        List<Task> collectionTasks = [SELECT Id, 
                                            Subject, 
                                            Description,
                                            Status,
                                            ActivityDate,
                                            WhatId,
                                            WhoId 
                                        FROM Task];
        Integer existingTaskLength = collectionTasks.size();

        for(Task ct :collectionTasks) {
            if(ct.ActivityDate <= System.today()) {
                ct.Status = 'Completed';
            }
        }

        Database.update(collectionTasks);

        CollectionsPlan__c upPlan = [SELECT 
                                            Id,
                                            Status__c,
                                            StartDate__c,
                                            Account__c,
                                            DunningMethod__c,
                                            CollectionsContact__c 
                                    FROM CollectionsPlan__c 
                                    LIMIT 1];
        System.debug(upPlan);

        upPlan.Status__c = 'Closed';

        Database.update(upPlan);
        
       List<Task> collectionTasksAfter = [SELECT Id, 
                                            Subject, 
                                            Description,
                                            Status,
                                            ActivityDate,
                                            WhatId,
                                            WhoId
                                        FROM Task];

        System.debug(collectionTasksAfter);
        System.debug(existingTaskLength);
        System.debug(collectionTasksAfter.size());

        System.assert(collectionTasksAfter.size() == existingTaskLength, 'No Tasks were deleted!');
    }

    
}